### ISSUE TITLE
[FEATURE]: new community sponsor Neovimconf

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#105]
https://neovimconf.live/

**Comment by Readpato** [comment]
@Wabri did they gave you their logo asset?

**Comment by Wabri** [comment]
![image](https://github.com/Schrodinger-Hat/schrodinger-hat-website/assets/12409541/7a0894ab-bf91-49cd-a1bc-abe5b033b5a1)

and 

https://github.com/Schrodinger-Hat/schrodinger-hat-website/assets/12409541/22b85200-f226-402d-8a64-6fcfde992ca9

Choose the one you prefer the most
