### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/schrodinger-hat-website#11]
It might be useful to add a PR template were to describe the mandatory things to add in the description of a PR.

I suggest adding the reference to a solving issue with closes or fixes keywords.

**Comment by Wabri** [comment]
We could also add to the project template here https://github.com/Schrodinger-Hat/SH-project-template

**Comment by davideimola** [comment]
Yes, sure!

**Comment by Readpato** [comment]
Hey there, I can take over this issue if needed :)
I could write some samples on how the PR template could look and then relay them here or over the discord server for feedback before creating a pull request. What do you think?

**Comment by Wabri** [comment]
All in your hands 🥇
