### ISSUE TITLE
Add issues template

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/schrodinger-hat-website#12]
It might be useful to add the Issue template, where to put the basic mandatory information while opening an Issue on this repository

**Comment by Wabri** [comment]
We could also add to the project template here https://github.com/Schrodinger-Hat/SH-project-template

**Comment by davideimola** [comment]
Yes sure!

**Comment by Readpato** [comment]
Hey there! I wasn't assigned to this issue but I tried to solved it with pull request #33 :)
