### ISSUE TITLE
Add discord server link

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/schrodinger-hat-website#14]
We want to advertise our Discord community server in the site!

Use the following link https://discord.gg/RTXr8A3eFn

**Comment by AlessandroB-96** [comment]
Proviamoci!

**Comment by VeroPap** [comment]
ci si prova

**Comment by davideimola** [comment]
Go for it @AlessandroB-96 and @VeroPap! If you need some help reach us!

**Comment by Wabri** [comment]
Even on readme?

**Comment by davideimola** [comment]
> Even on readme?

Hi @Wabri,
Pheraps we can put the link inside the organization's README.

I do not see any pros to put the link in the README of this repository!

**Comment by Wabri** [comment]
Yes you are right
