### ISSUE TITLE
Dark mode not work with community partner

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#17]
When in dark mode the grusp logos not change:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/12409541/168656794-567124eb-d4ff-4dda-9c9b-556ccf936b8f.png">

The background of the image should be transparent

**Comment by senali-d** [comment]
I prefer to work on this issue. Can you explain the issue in detail please. 

The background of the image should be transparent - only the dark mode or in both dark and light mode?

**Comment by davideimola** [comment]
Hi @senali-d! I am sorry @LucaFin has already done it!

I think you can ask to be assigned to the next issue if you want. 

It is not yet ready!

**Comment by senali-d** [comment]
@[davideimola](https://github.com/davideimola) okay thanks.
