### ISSUE TITLE
Change it and eng cover messages

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/schrodinger-hat-website#19]
We want to change the yt cover messages of our site.

**Comment by Wabri** [comment]
Did you mean this:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/12409541/168752616-598d02d6-fe78-44b2-b6e4-e59f1ec92925.png">

**Comment by davideimola** [comment]
Yes @Wabri! As now it is more a community then a podcast I would like to change it!

What ara your suggestions to this?

**Comment by Wabri** [comment]
But at the moment we could make this small change actually so that there is no confusion. Maybe just putting the link to discord and opencollective which are the most important ones.

link discord: https://discord.com/invite/e88KqV343c
link opencollective: https://opencollective.com/schrodinger-hat

**Comment by 404answernotfound** [comment]
gtm

**Comment by davideimola** [comment]
It may be a good solution @Wabri! I didn't recall that @404answernotfound and @AngyDev were restyling the homepage!

I can suggest changing either the Italian and English initial phrases. I don't think it might take longer to change those things.

**Comment by Readpato** [comment]
Hey there. I think this issue can be closed since it was fixed with pull request #29 :)

**Comment by davideimola** [comment]
Yes, thanks @Readpato!
