### ISSUE TITLE
Headline of site seams wrong

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#20]
the website https://www.schrodinger-hat.it/ still contains the old headline, maybe replacing "podcast" with "community" would be more appropriate.

![image](https://user-images.githubusercontent.com/12409541/172784813-71f5d9bc-f242-4402-8e7f-3c8554fb51a2.png)

Maybe edit it by removing "first" because someone might disagree.

"An Italian open source community" might work?

**Comment by TheJoin95** [comment]
I agree with the new headline. The text is inside the i18n file

**Comment by Readpato** [comment]
Hey I can take over this issue if you want :)

**Comment by TheJoin95** [comment]
Sure, go ahead! :)

**Comment by Wabri** [comment]
Thank you @Readpato ✌️
