### ISSUE TITLE
Broken logo

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#21]
Missing GRUSP logo on the event page of opensourceday2021?

![image](https://user-images.githubusercontent.com/12409541/177976372-04c35f80-1f6c-4cff-815b-35f8923fa5f8.png)

https://www.schrodinger-hat.it/events/open-source-day-2021-florence-student-hotel

**Comment by Readpato** [comment]
I can take over this issue if needed! Is the logo from Grusp available anywhere to be downloaded or do we have it already?

**Comment by Wabri** [comment]
You can use the same found in the main page 😊
