### ISSUE TITLE
Add pisa.dev logo to community partners

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#22]
update Community Partners with the pisa.dev logo:

![image](https://user-images.githubusercontent.com/12409541/179461595-4f08fea4-ee5c-47af-b06f-4b158a73b83d.png)

Logo: https://pisa.dev/logo2.svg & https://pisa.dev/logo.svg
Site: [boia.dev](http://boia.dev/)

**Comment by 404answernotfound** [comment]
@AngyDev vuoi occupartene tu? :D

**Comment by AngyDev** [comment]
@404answernotfound ok ci penso io
