### ISSUE TITLE
Team page update

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#24]
There are more team members that are waiting to be added in the dedicated page: https://www.schrodinger-hat.it/team

This is the list of the members: https://github.com/Schrodinger-Hat/Contributors

**Comment by sparsh-007** [comment]
can i work on it?

**Comment by sparsh-007** [comment]
\assign

**Comment by Wabri** [comment]
Of course you can 👍

**Comment by sparsh-007** [comment]
<img width="1440" alt="Screenshot 2022-07-27 at 1 31 21 AM" src="https://user-images.githubusercontent.com/93381005/181103248-673e2d36-be80-4431-9f90-1f01d6f13e7b.png">
 
I came across error while putting this description it seems too big
