### ISSUE TITLE
Enforcing the node version

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/schrodinger-hat-website#3]
We want to introduce some sort of enforcement for the Node version.

We can set this thing by using:

- package.json node and npm engine versions
- a `.nvmrc` file for nvm users
- configuring volta in the repository

Probably I will go with setting all these three enforcement, but I am open to other ideas!

@gianfabiopezzolla @Wabri @404answernotfound @TheJoin95  what are your thoughts?

**Comment by 404answernotfound** [comment]
I'm not against Volta usage if it can coexist and there's no "mutex" problems with nvm.

I'd advise to go for a ```.nvmrc``` usage, with node versions > 14

**Comment by TheJoin95** [comment]
Go for it, let's find out how volta is working.
In the worst scenario we are going to simple remove it from the project :)

**Comment by davideimola** [comment]
Yeah, I'm on the same page with your thoughts. If Volta has no major issues inside the project I think we can easily support it.

Probably I suggest being more strict with the version because we can create different incidents if someone uses a different major version of Node.
