### ISSUE TITLE
Team Page restyling

### ISSUE THREAD

**Issue by davideimola** [Schrodinger-Hat/schrodinger-hat-website#31]
The currently deployed team page has too much information, and continuously adding contributors may be a bit complicated to handle.

The proposal is to have a page like the following image. We can add an action with a link to open a modal with a full Bio and further information.

![image](https://user-images.githubusercontent.com/14623986/184112583-3f5e1f84-ad02-4e35-9172-93cb54ba24c8.png)

**Comment by davideimola** [comment]
@Wabri what do you think?

**Comment by Wabri** [comment]
LGMT

**Comment by TheJoin95** [comment]
Should we still considering this issue as to do?

**Comment by Wabri** [comment]
Maybe we can remove the useless description of every members

**Comment by rennavittorio** [comment]
Hi all! As I mentioned to one of the contributors @davideimola, I'd like to handle this issue if it's still open! Please let me know :)

**Comment by rennavittorio** [comment]
Hi @Wabri, @Readpato, nice to meet you! 🚀🚀
Thanks for the feedback, I'll check the first repo you mentioned, and I think I'll start from there because I'm more confident with Vue3, ok?
I've already joined the discord channel, if you'd like, let's catch up once via call, to get to know each other a bit, and get a brief overview of the project!

**Comment by rennavittorio** [comment]
Hey, how you doin? @Readpato @davideimola @Wabri 
Here's the link to the changes I applied to my forked repo (from Pato's repo): https://github.com/Readpato/schrodinger-hat-website/compare/main...rennavittorio:schrodinger-hat-website:feat/redesign-team-page, any feedback will be really appreciated!
@Readpato and I think it will be better to create a PR directly on the future repo (post-migration to VUE3), what do you think about it?
Let me know!
Have a nice weekend 🍻
:)

**Comment by Readpato** [comment]
When you are about to create the PR @rennavittorio, please add the following in your PR description "Closes #31" so we it closes this issue automatically!
