### ISSUE TITLE
[FEATURE]: Update Vue2 to Vue3

### ISSUE THREAD

**Issue by Readpato** [Schrodinger-Hat/schrodinger-hat-website#42]
## Feature request

This issue aims to propose the update of the Vue version used in this project (v2.6.14), to its newest version [Vue3](https://vuejs.org/).

### Why is it needed?

The main reason for this feature is because Vue2 will enter [EOL in December 2023](https://v2.vuejs.org/lts/). Which means it will no longer receive updates, including security and browser compatibility fixes.
 
### What will improve?
 
 This feature will allow us to utilize all the new features that come integrated with Vue 3, such as:

- [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html) to point out a few advantages: greatly improves the DX, introduces the [<script setup>](https://vuejs.org/api/sfc-script-setup.html#script-setup) syntax sugar, [offers a smaller production bundle](https://vuejs.org/guide/extras/composition-api-faq.html#smaller-production-bundle-and-less-overhead), etc.

- First class [Typescript support](https://vuejs.org/guide/typescript/overview.html#using-vue-with-typescript) as it was written completely in [Typescript](https://www.typescriptlang.org/). This also offers a good [Typescript experience with the Composition API](https://vuejs.org/guide/typescript/composition-api.html).

Migrating to Vue3 will also allow us to utilize different libraries that have been created and/or improved this past years and at the same time, to stay up to date to any new changes in the web development world. To name a few examples:

- [Vite](https://vitejs.dev/) which is super fast when building and also while working on development mode.
- [Vitest](https://vitest.dev/) which is native to Vite and allows us to create faster and easier unit tests, [more info](https://vitest.dev/guide/why.html).
- [Cypress v12](https://docs.cypress.io/guides/overview/why-cypress#Cypress-ecosystem) which allows us to write more robust E2E tests.
- [Vue i18n v9](https://vue-i18n.intlify.dev/) which includes [new features](https://vue-i18n.intlify.dev/guide/migration/features.html) that could be implemented along with Vue3.

### How will this be achieved?

I think the best way to implement this feature will be to follow the [official Vue3 migration guide](https://v3-migration.vuejs.org/), which provides a thorough explanation on how to correctly migrate an app from Vue2 to Vue3. 

For further assistance, there is additional content that could ease and help the transition between versions.

- [Alex Van Liew presents “How we migrated our HUGE app to Vue 3” at VueConf US 2022](https://youtu.be/lPfp9XZINrg). This talk also answers a critical question "Why migrate now (or at all)?"
- [Marina Mosti - Migrating Vue 2 to Vue 3 - Vuejs Amsterdam 2021](https://youtu.be/9Eh5bMX_lqM)
- [Daniel Kelly: How to Migrate from Vue CLI to Vite – vuejs.de Conf 2022](https://youtu.be/PAT7SbdTBjI)

**Additional content/notes**

I think the transition from Vue2 to Vue3 is a step forward for this project. Not only will it allow us to keep updated with the latest Vue ecosystem updates, it will also allow new developers that are learning Vue or are searching a nice Open Source project to contribute to, to easily get onboard and start contributing.

**Comment by Readpato** [comment]
Hey there! I could start tackling this issue if we think that these changes are worth doing :)

**Comment by Wabri** [comment]
Awesome Pato, this upgrade had to be done one way or another and I'm happy that you want to do it 😃

**Comment by Readpato** [comment]
Super! I'll get started then 💪
