### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#76]
![pulpfiction](https://github.com/Schrodinger-Hat/schrodinger-hat-website/assets/12409541/3491850d-96f6-4ad7-bcde-0b5d92530f99)

No license included in the code, we need to add one!

https://choosealicense.com/

**Comment by TheJoin95** [comment]
We should not use MIT. We see a lot of people not giving credits to us

**Comment by Readpato** [comment]
Asking from ignorance, do we need to ask about giving credit to us about something from the website?
I could research what other possibilities there are though

**Comment by TheJoin95** [comment]
To be honest, I don't want to risk anything like the things happened for image go nord: a lot of people were using or forking it then renamed without asking or else

So, I prefer to have a stronger and strict license

**Comment by Readpato** [comment]
Totally understandable :)
I'll research a little bit more and come back with some options!
