### ISSUE TITLE
[FEATURE]: Add new contributors to Team page

### ISSUE THREAD

**Issue by 404answernotfound** [Schrodinger-Hat/schrodinger-hat-website#79]
Add missing contributors from Team page

**Comment by Readpato** [comment]
This one could be directly expanded on #62, want to transpose it over there?

**Comment by rennavittorio** [comment]
Hi mates, 

@Readpato @404answernotfound here a brief to-do on how I think we could do this and maybe standardize a little the process of collecting info and adding new contributors to the website:

- [ ]  create a template in g-sheets to collect current online contributors (with related info) => it could be also another similar file, maybe here on GitHub like the README, do you have any idea?
- [ ]  share the template with the community and collect missing contributors (with related info)
    - [ ]  TBD - use the template as a community standard => if so, we need eventually some sort of repo to store the file, and give access to contributors/maintainers
- [ ]  add missing contributors to the website

Let me know what you think about it, I'm open to any ideas :)

**Comment by Readpato** [comment]
Hey @rennavittorio, I love the initiative!
Justo one thing, lets keep the information centralized, could you please transfer your comment to #62 and we will continue the discussion over there? By doing this we avoid duplicated issues.
I'll be closing this issue now :)
