### ISSUE TITLE
secondary image onhover (team page)

### ISSUE THREAD

**Issue by 404answernotfound** [Schrodinger-Hat/schrodinger-hat-website#8]
The code for a secondary image on hover is already in the team page.

The html and css part need to be uncommented and possibily, we could also add our favorite songs during the hover event.

What do you think?

**Comment by BrianSteel** [comment]
No particular difference between the commented and uncommented code as only the same image gets shown. I feel secondary image is not necessary.

Adding songs to each team member panel is cool. Adding a music play wave at the bottom right with it on hover would make it look nicer.

**Comment by 404answernotfound** [comment]
> No particular difference between the commented and uncommented code as only the same image gets shown. I feel secondary image is not necessary.
> 
> Adding songs to each team member panel is cool. Adding a music play wave at the bottom right with it on hover would make it look nicer.

Well, to notice a difference you'd have to go to the configuration and set a different "secondaryImage" to be used. Also, remember to uncomment the html and css, otherwise it wouldnt work :)

As per the music, sounds like an amazing idea! Wanna work on it? :D

**Comment by BrianSteel** [comment]
Yes, I had seen the messages.json where the "secondaryImage" key was present and uncommented both html and css code.

Yeah sure. I can try it. Btw you meant work on adding the music and the music play wave right? On more thing about the npm version. Is there any specific reason for using "6.14.15" version? Last time, I just overrode this configuration to make it work. I will need to install the versions.

**Comment by 404answernotfound** [comment]
we are using specific nodejs version (14.18) for the netlify build, the npm versioning comes with that

**Comment by BrianSteel** [comment]
So, I checked it out. I am having trouble with the message.json not updating when I change it. Do you know what's the issue? Plus, chrome does not allow music to be played onHover or mouseEnter. Some type of user action is required such as a click.

**Comment by Readpato** [comment]
Is this still a feature you want implemented @404answernotfound ? If yes, I would wait for the new Team Page restyling to be merged (#31). Otherwise I would close this issue as it is no longer needed

**Comment by rennavittorio** [comment]
> 

I'll follow the thread, let me know in case :)

**Comment by Readpato** [comment]
Closing this as is it's stale. Open a new issue if needed

**Comment by Readpato** [comment]
Closing this as is it's stale. Open a new issue if needed
