### ISSUE TITLE
[FEATURE]: Create schrodinger session page

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/schrodinger-hat-website#96]
## Session page

A page where we have a list of our session, filtered by city.
Then a detail page for each of our events.

- you can get inspiration on the UI from other website

**Comment by rennavittorio** [comment]
Hi @TheJoin95, I'm interested in trying

**Comment by Wabri** [comment]
There is also the last event in Milan that has not yet been added to the site https://www.youtube.com/watch?v=-5vruASGj4M

**Comment by rennavittorio** [comment]
@AngyDev @Readpato Hi there! 
I am writing here some points on which I would like to talk about and get your opinion:
- review of the current state of the new page (with a little focus on filters)
- the possibility to move the events data from message.ts in a new file (ie. events.ts) with a new data configuration (if I remember correctly, the simplification of that file was also one of your idea @Readpato)
- the logic behind the main card and the possible sorting of the little cards @AngyDev 
- (off-topic) the possibility to use UnoCSS config file to manage project style variables (eg. primary and secondary brand colors)
I'm open for an evening where we can have a call to talk about it (and have a beer 🍺 ), let me know!

**Comment by Readpato** [comment]
I like this idea! Like we spoke, you can open a draft PR and we can progressively review it so we don't have to review a big PR in the end. Lemme know! You can also link this issue to the PR
