### ISSUE TITLE
refactor: OSDay Banner and Button

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#97]
Maybe we should replace the "spotify" button with a "github" button in the main page of the website

![image](https://github.com/Schrodinger-Hat/schrodinger-hat-website/assets/12409541/3be58683-c942-43b4-acfb-fc8ae13f1209)

The first one on the left

**Comment by TheJoin95** [comment]
I think we can open source day button

Il mer 20 set 2023, 18:10 Patrick Raedler ***@***.***> ha
scritto:

**Comment by Readpato** [comment]
Could be done as well! No problem =] 
Risking to take this issue a little bit off topic but, do we also want to create something more "flashy" for Open Source Day. Like a banner on top of the page? As an example, enter here and look at the top: https://vuejs.org/

**Comment by Readpato** [comment]
What would we like to be displayed on the banner?

- Announcement text
- Link to the website
- Icon? (Idk if we have one specific for OSDay)

**Comment by Wabri** [comment]
We do not have a specific icon for osday, we should create one you are right. For now, I think we can put a text with OSDay24 and a redirect to 2024.osday.dev 👍
