### ISSUE TITLE
[BUG]: Title+Meta are old

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/schrodinger-hat-website#98]
Hello here to present an old refuse :)

https://github.com/Schrodinger-Hat/schrodinger-hat-website/blob/3b561f4df871ea1170460adc6a7b52be2de6db17/index.html#L16

https://github.com/Schrodinger-Hat/schrodinger-hat-website/blob/3b561f4df871ea1170460adc6a7b52be2de6db17/index.html#L19

Title => Schrödinger Hat
Meta content => An Open Source community

**Comment by Readpato** [comment]
Nice catch!

I'm going to take the opportunity and work on this Bug while doing https://github.com/Schrodinger-Hat/schrodinger-hat-website/issues/93
